spring.application.name=adapters
application.version=1.0.0
application.title= Tickup - Subs

server.port=9000
spring.banner.charset=UTF-8
joinfaces.faces.PROJECT_STAGE=Development
joinfaces.faces-servlet.name=FacesServlet
joinfaces.faces-servlet.url-mappings=/faces/*,*.jsf,*.faces,*.xhtml
joinfaces.primefaces.theme=poseidon-#{guestPreferences.theme}
joinfaces.primefaces.submit=partial
joinfaces.primefaces.move-scripts-to-bottom=true
joinfaces.mojarra.number-of-views-in-session=15
joinfaces.mojarra.compress-view-state=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://mariadb:3306/tickupDB?createDatabaseIfNotExist=true
spring.datasource.url=jdbc:mariadb://localhost:3306/tickupDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.main.allow-circular-references=true
spring.jpa.hibernate.ddl-auto=create-drop
# Mail config pparams
spring.mail.password=Alter372625@
spring.mail.host=mail.infomaniak.com
spring.mail.properties.mail.smtp.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.username=devmail@it-centrex.com
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
secret-key=efd703de6187cf8276fd8013e8aa5f443b6b67812163eb7f40bc86c4fe499f0ef1c79e967d13abe046dee07102ea4c3ce881f0514cf510c575304b5c4fe5be2b78e86e42ecbcd6466ed01534f67b54eff5521c2e3094fd869915bb715f34edb7273bef9c44642dcb45daed0b19be13f47c9235e16f481871d4a43947c5a176191d0dc597176c58c69ec6267e7fbbf3240ed07901896ee84a604b578aa0aba90b985b2698c253b31650936837b7b31833634c2aa8617b090bd940a6cfd6acb47ce5297619fda477f918b8a0cef1bbe6c5e6c6d03f431191e9088962c3e771a707f6794372464224c5a1ea9688a1eda0a4e02bdc550385f9239e36a308ef9a759c

# Tickup notify url
tickup.notify.url=http://localhost:9001/api/v1
