spring.application.name=adapters
application.version=1.0.0
application.title=eTix

server.port=9000
spring.banner.charset=UTF-8
joinfaces.faces.PROJECT_STAGE=Development
joinfaces.faces-servlet.name=FacesServlet
joinfaces.faces-servlet.url-mappings=/faces/*,*.jsf,*.faces,*.xhtml
joinfaces.primefaces.theme=poseidon-#{guestPreferences.theme}
joinfaces.primefaces.submit=partial
joinfaces.primefaces.move-scripts-to-bottom=true
joinfaces.mojarra.number-of-views-in-session=15
joinfaces.mojarra.compress-view-state=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/etixDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.main.allow-circular-references=true
spring.jpa.hibernate.ddl-auto=update
# Mail config pparams
spring.mail.password=Alter372625@
spring.mail.host=mail.infomaniak.com
spring.mail.properties.mail.smtp.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.username=devmail@it-centrex.com
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

