spring.application.name=adapters
server.port=9000
spring.banner.charset=UTF-8
joinfaces.faces.PROJECT_STAGE=Development
joinfaces.faces-servlet.name=FacesServlet
joinfaces.faces-servlet.url-mappings=/faces/*,*.jsf,*.faces,*.xhtml
joinfaces.primefaces.theme=poseidon-#{guestPreferences.theme}
joinfaces.primefaces.submit=partial
joinfaces.primefaces.move-scripts-to-bottom=true
joinfaces.mojarra.number-of-views-in-session=15
joinfaces.mojarra.compress-view-state=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/etixDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.main.allow-circular-references=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.web=DEBUG


// Paytech API
paytech.api.key=0915c8c6b5edddd5566715152a85925d8eb320fab43482ef4a311c6119013cb2
paytech.api.secret=54f19aefd2e866271e306177de0b2685bddfb5458ae32ffe3d665a45fd16948d
paytech.devise=XOF

// CinetPay API
cinetpay.api.key=200349002765f8799f5df790.27967324
cinetpay.api.secret=1255514423673df0903ffc27.73762750
cinetpay.site.id=5883393

// FedaPay API
fedapay.api.key=pk_sandbox_hNO31PWCieS4VeKT0uszDZJk
fedapay.api.secret=sk_sandbox_90UI4B9zGGuk8OxdgLg1lrOR